//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace StackOverflow.Net.Mvc.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StackOverflowContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StackOverflowContainer object using the connection string found in the 'StackOverflowContainer' section of the application configuration file.
        /// </summary>
        public StackOverflowContainer() : base("name=StackOverflowContainer", "StackOverflowContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StackOverflowContainer object.
        /// </summary>
        public StackOverflowContainer(string connectionString) : base(connectionString, "StackOverflowContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StackOverflowContainer object.
        /// </summary>
        public StackOverflowContainer(EntityConnection connection) : base(connection, "StackOverflowContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion
    
    
}
